### ISSUE TITLE
HTTPS connections not working

### ISSUE THREAD

**Issue by vwbij** [mvf/svn_wfx#1]
Hi,
First, thank you very much for sharing this code. Browsing SVN repositorys with TC is a very usefull thing! 

I have problems to find/compile the appropriate dependencies. Does anybody has got some hints? For me, building of SVN, APR and co is very complicated. Does anybody have got precompiled DLL's with libs for a actual version of SVN? At the moment I've got it running with older libs and the dll's of 1.9.4. 

It works, but if I select a repo that needs authentication, svn_client_list2 produces a error "No provider registered for 'svn.ssl.server'". But I see, in "initSvn" a simple_promt_provider and a username_prompt_provider is successful (as I can see) registered. Does anybody know why it does not work? Is maybe Cyrus SSL missing in the librarys? 

Thank you, all the Best,

Volker Bijewitz

**Comment by mvf** [comment]
Hi Volker,

thanks a lot for your interest in this ancient and buggy program. ;)

I can reproduce the HTTPS connection issue. It probably isn't a library problem since it works just fine with an svn command-line client built against the same libs. Until there's a fix you could try using ssh+svn instead.

Regarding the build, there don't seem to be any pre-built libraries for Subversion 1.9.5 and building from source on Windows looks just painful with all those dependencies. The stable version from here works for me: https://sourceforge.net/projects/win32svn/files/1.8.17/apache24/. I pushed an updated .vcproj for this version.

Cheers,
Matthias

**Comment by vwbij** [comment]
Ok, thank you very much for fixing the https issues. I give it a try. I have found that "ssh+svn" does not work connecting to our SVN serner. No idea why. 

Compiling SVN is really complicated, I've made a little progress, but does not succeed. I think I use 1.8.17.

Have a nice Weekend,

Volker
